server:
 port: 8040

spring:
 application:
   name: microservice-gateway-zuul-aggregation
         
info:
 app:
  name: @project.artifactId@
  encoding: @project.build.sourceEncoding@
  java: 
    source: @java.version@
    target: @java.version@
    
user: 
 userServiceUrl: http://microservice-gateway-zuul/
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
    instance:
      perfer-ip-address: true
      
logging:
  level:
   com.yibo.application.controller.UserFeignClient: DEBUG
   
    
management:
  security:
    enabled: false
  