server:
 port: 8011

spring:
 application:
   name: microservice-consumer-movie
         
info:
 app:
  name: @project.artifactId@
  encoding: @project.build.sourceEncoding@
  java: 
    source: @java.version@
    target: @java.version@
    
user: 
 userServiceUrl: http://localhost:8000/
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
    instance:
      perfer-ip-address: true