spring:
  application:
    name: yibo's eureka server
---
spring:
  profiles: peer1
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://user:password123@peer2:8762/eureka
---
spring:
  profiles: peer2
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port : 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://user:password123@peer1:8761/eureka